# Generated by Django 5.0.6 on 2026-06-30 10:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=512)),
                ('kind', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel')], max_length=16)),
                ('path', models.CharField(max_length=1024)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('columns', models.JSONField(default=list)),
                ('preview_rows', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nl_prompt', models.TextField()),
                ('replacement_value', models.TextField(blank=True, default='')),
                ('target_columns', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('stage', models.CharField(blank=True, default='queued', max_length=64)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('regex_pattern', models.TextField(blank=True, default='')),
                ('regex_source', models.CharField(blank=True, choices=[('cache', 'Redis cache'), ('llm', 'LLM'), ('heuristic', 'Heuristic fallback')], default='', max_length=16)),
                ('regex_explanation', models.TextField(blank=True, default='')),
                ('result_path', models.CharField(blank=True, default='', max_length=1024)),
                ('total_rows', models.BigIntegerField(blank=True, null=True)),
                ('matched_rows', models.BigIntegerField(blank=True, null=True)),
                ('result_columns', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.uploadedfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
