# Generated by Django 5.0.6 on 2026-07-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='preview_rows',
        ),
    ]
